### ISSUE TITLE
Jason.Encoder not implemented

### ISSUE THREAD

**Issue by philippneugebauer** [elixir-addicts/rollbax#90] opened 2018-03-03 22:29 UTC
I have opened an issue for `jason` yesterday, but after reconsidering it tonight, I guess `rollbax` might be the better place to fix it.

Due to some unexpected errors, I got a lot of rollbax crashes and therefore no information about my errors, when you really want to have the information. They weren't sent because of the following:
```
09:40:56.159 [error] GenServer Rollbax.Client terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for {"id", "2"}, Jason.Encoder protocol must always be explicitly implemented. This protocol is implemented for: Any, Atom, BitString, Date, DateTime, Decimal, Float, Integer, Jason.Fragment, List, Map, NaiveDateTime, Time
    lib/encoder.ex:128: Jason.Encoder.Any.encode/2
    lib/encode.ex:138: Jason.Encode.list/3
    lib/encode.ex:172: Jason.Encode.map_naive_loop/3
    lib/encode.ex:173: Jason.Encode.map_naive_loop/3
    lib/encode.ex:162: Jason.Encode.map_naive/3
    lib/encode.ex:172: Jason.Encode.map_naive_loop/3
    lib/encode.ex:173: Jason.Encode.map_naive_loop/3
    lib/encode.ex:162: Jason.Encode.map_naive/3
```

**Comment by whatyouhide** [comment] 2018-03-04 22:29
I tried reproducing this but it's been really hard as I don't think we are adding something in the shape of `{"id", "2"}` to the event being reported to Rollbar (and hence encoded through Jason). My guess is that we're not transforming something that we should transform to a string. Do you have something that can reproduce this?

**Comment by philippneugebauer** [comment] 2018-03-05 00:46
https://github.com/philippneugebauer/rollbax_fail

It's a `phoenix` application.

So you need to set up your database first. Create a user with random data and then access the user via `/users/1/ and you should get the error. I haven't set up the rollbax application so you need to enter the token. The `aws` stuff should be fine without doing anything.

**Comment by whatyouhide** [comment] 2018-03-06 00:10
I:

* downloaded the repo
* ran `mix deps.get`
* ran `mix do ecto.create, ecto.migrate
* ran `cd assets && npm install && cd ..`
* ran `iex -S mix phx.server`
* navigated to http://localhost:4000/user/1

and the error I get is:

<details>
 <summary>Error details</summary>
[error] #PID<0.492.0> running RollbaxFailWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /users/1
** (exit) an exception was raised:
    ** (KeyError) key :file_name not found in: %RollbaxFailWeb.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, avatar: nil, id: 1, inserted_at: ~N[2018-03-05 23:50:59.606221], name: "foo", updated_at: ~N[2018-03-05 23:50:59.608758]}
        (arc) lib/arc/definition/versioning.ex:15: Arc.Definition.Versioning.resolve_file_name/3
        (arc) lib/arc/storage/s3.ex:91: Arc.Storage.S3.s3_key/3
        (arc) lib/arc/storage/s3.ex:72: Arc.Storage.S3.build_url/4
        (rollbax_fail) lib/rollbax_fail_web/templates/user/show.html.eex:12: RollbaxFailWeb.UserView."show.html"/1
        (rollbax_fail) lib/rollbax_fail_web/templates/layout/app.html.eex:29: RollbaxFailWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (rollbax_fail) lib/rollbax_fail_web/controllers/user_controller.ex:2: RollbaxFailWeb.UserController.action/2
        (rollbax_fail) lib/rollbax_fail_web/controllers/user_controller.ex:2: RollbaxFailWeb.UserController.phoenix_controller_pipeline/2
        (rollbax_fail) lib/rollbax_fail_web/endpoint.ex:1: RollbaxFailWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (rollbax_fail) lib/rollbax_fail_web/endpoint.ex:1: RollbaxFailWeb.Endpoint.plug_builder_call/2
        (rollbax_fail) lib/plug/debugger.ex:99: RollbaxFailWeb.Endpoint."call (overridable 3)"/2
        (rollbax_fail) lib/rollbax_fail_web/endpoint.ex:1: RollbaxFailWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/andrea/tmp/rollbax_fail/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
</details>

which is not captured by Rollbax (as it's a ranch/cowboy/Plug error, we still need to implement that) and doesn't trigger the error you mentioned.

It would be really helpful if you could reduce the size of your application and make it as small as possible while still reproducing the error. Try including detailed steps to reproduce so that I can reproduce it on my local machine as well and debug it :) Thanks! :heart_decoration:

**Comment by philippneugebauer** [comment] 2018-03-06 00:50
Yeah, you're on the right way. The report of this error leads then to the crash of `rollbax`. I did not really know what's the best way to setup `rollbax` for demonstration, so if you could give my some hints about for local reproduction of `rollbax` errors, I gladly implement them.

Does the following calls `rollbax` as well or is it just calling a logger and bypassing the rollbax code?

```
config :rollbax, enabled: :log
```

**Comment by JonRowe** [comment] 2018-03-06 10:05
I'm getting this when reporting crashes too I think its due to params not being loaded...

```elixir
[error] GenServer Rollbax.Client terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Plug.Conn.Unfetched{aspect: :params}, Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:
    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:
    defstruct ...

    @derive Jason.Encoder

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:
. This protocol is implemented for: Any, Atom, BitString, Date, DateTime, Decimal, Float, Integer, Jason.Fragment, List, Map, NaiveDateTime, Time
    lib/encoder.ex:100: Jason.Encoder.Any.encode/2
    lib/encode.ex:161: Jason.Encode.map_naive/3
    Protocol.derive(Jason.ENcoder, NameOfTheStruct)
    lib/encode.ex:162: Jason.Encode.map_naive/3
    lib/encode.ex:172: Jason.Encode.map_naive_loop/3
    lib/encode.ex:35: Jason.Encode.encode/2
    lib/encode.ex:162: Jason.Encode.map_naive/3
    lib/encode.ex:172: Jason.Encode.map_naive_loop/3
Last message: {:"$gen_cast", {:emit, {"error", 1520312910, %{"trace" => %{"exception" => %{"class" => "ErrorModule", "message" => "Actual Error"}, "frames" => []}}, %{params: %Plug.Conn.Unfetched{aspect: :params}}, %{}}}}
    (rollbax) lib/rollbax/client.ex:70: Rollbax.Client.handle_cast/2
```

**Comment by whatyouhide** [comment] 2018-03-06 10:28
I'm having trouble understanding how this is reported by Rollbax. Are you reporting this manually? Because you didn't have `enable_crash_reports: true` in the repo that you provided to reproduce this.

**Comment by philippneugebauer** [comment] 2018-03-06 10:29
I don't know. My settings are exactly as in the repository and it reported it. I didn't do it manually.

**Comment by whatyouhide** [comment] 2018-03-06 10:46
@philippneugebauer and are you seeing the error in Rollbar (on the web), or locally?

@JonRowe what about you, are you reporting this manually?

**Comment by philippneugebauer** [comment] 2018-03-06 10:47
No, it doesn't make its way into Rollbar, I just had a look into the docker logs to figure out what crashed.

**Comment by JonRowe** [comment] 2018-03-06 10:47
@whatyouhide no I configured `enable_crash_reports: true`, I am seeing the crash on rollbar, but its this error (the Jason encoding) not the original source error.

**Comment by whatyouhide** [comment] 2018-03-06 10:51
@JonRowe could you provide a minimal repository that reproduces this? Something I can clone and steps to reproduce this error. That would be super helpful 💟

**Comment by JonRowe** [comment] 2018-03-07 00:15
This repo recreates it https://github.com/JonRowe/rollbax-error-example, hitting any route will cause an error which is not properly reported. Looking at it though its my use of:

```elixir
defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
  Rollbax.report(kind, reason, stacktrace, %{params: conn.params})
end
```

Thats the issue, which is straight out of the docs but bails if it can't encode the last part...

**Comment by prem-prakash** [comment] 2018-03-21 13:35
Same issue on sentry
https://github.com/getsentry/sentry-elixir/issues/240

What services like Rollbar and Sentry must understand is that as many functions on elixir returns tuples, and tuples can't be encoded in JSON, this case must be treated.

One simple way would be to add a key, and the tuple as a value, so it can be encoded as JSON.

**Comment by whatyouhide** [comment] 2018-03-26 13:49
I improved the documentation page mentioned by @JonRowe in 7ff1181b0f8e2ed1878b5bb4c8496f9eda144510 so that it doesn't have the same bug. @philippneugebauer still hasn't provided a minimal failing example, so I am closing this for now as I can't act on it. Please feel free to ping here or reopen if this error still happens.

**Closed by whatyouhide** 2018-03-26 13:49 UTC

**Comment by philippneugebauer** [comment] 2018-03-26 13:51
I did: https://github.com/philippneugebauer/rollbax_fail

**Comment by whatyouhide** [comment] 2018-03-26 13:53
@philippneugebauer as I said in https://github.com/elixir-addicts/rollbax/issues/90#issuecomment-370613673, I cannot reproduce this in a simple way as the steps you outlined don't work for me.

I'll say the same:

> It would be really helpful if you could reduce the size of your application and make it as small as possible while still reproducing the error. Try including detailed steps to reproduce so that I can reproduce it on my local machine as well and debug it :)

Thanks! 💟

**Comment by philippneugebauer** [comment] 2018-03-26 13:55
@whatyouhide It's the minimal example I provided. I just encountered this error when I did an error in development, which then caused `Rollbar` to crash, because it couldn't handle tuples the right way.

**Comment by JonRowe** [comment] 2018-03-26 23:04
FWIW Plug 1.5.0 has resolved a symptom of this, as their exceptions now have default messages.

**Comment by philippneugebauer** [comment] 2018-04-24 16:09
I found out that the phoenix plug code caused my crashes, in particular the params fetching: https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html

It looks like it has been refactored since that, but the following made it working for me.

```
    params =
      for {key, value} <- conn.params do
        if key in ["password", "password_confirmation"] do
          %{key => "[FILTERED]"}
        else
          %{key => value}
        end
      end
```
