### ISSUE TITLE
errors when starting an application, e.g. after a deploy or reboot

### ISSUE THREAD

**Issue by adamkittelson** [elixir-addicts/rollbax#23] opened 2016-06-02 18:56 UTC
I'm getting errors similar to this https://gist.github.com/adamkittelson/65523e2c34f15b26b57825c81a4e6c1d when my application first starts.

My best guess is that it's happening because I've added Rollbax.Notifier to my Logger backends as per the readme and that the exception is being raised for log messages that are sent to that backend before the Rollbax.Client GenServer has had a chance to start / register itself.

I think it could be solved similarly to what the Honeybadger library is doing, i.e. if the user configures Rollbax to use the Logger backend then Rollbax can add Rollbax.Notifier as a hander after the Rollbax.Client is running, similar to this: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger.ex#L114-L116

Thanks for putting this library together, I was glad to see it existed. While I don't think Airbrake / Honeybadger are necessarily overpriced, I also don't want my error tracking costs to be equivalent to my hosting costs for my side project so Rollbar's free plan is perfect for what I need.

**Comment by whatyouhide** [comment] 2016-06-03 15:12
I'll look into this as soon as I have some time :)

**Comment by whatyouhide** [comment] 2016-06-08 16:40
@adamkittelson do you have anything to reproduce this? It would make my life a bit easier 😄

**Comment by whatyouhide** [comment] 2016-06-09 15:33
@adamkittelson I tried reproducing this for a little while but I was not able to; I talked about this with @lexmag as well and we can think of two reasons why this happens:

1. you have `:rollbax` in your `:included_applications` and you're not manually starting it or you're writing to `Logger` before starting `:rollbax` (this is unlikely though)
2. you have `[:logger, :x, :rollbax]` in your applications and `:x` is writing to the logger; in this case `[:logger, :rollbax, :x]` is the way to go.

In both cases, we pushed a fix in 21f53b18c55379ffd55fb23de7d0c79f1bc5221e that only warns when trying to talk to the `Rollbax.Client` GenServer instead of crashing. Can you try out master and see if it fixes it? Also, are you doing 1. or 2.? :)

**Comment by adamkittelson** [comment] 2016-06-11 23:37
I can confirm that your fix checking if the Rollbax.Client genserver is alive before casting to it prevents the crash (although personally I think holding off on adding the rollbax logger backend to the logger genevent process until it's running is a bit cleaner than checking if it's alive before every emit message.)

I dug into what was causing the error before rollbax is ready. I'm not using `:included_applications` so 1. is out. It is being caused by one of my other dependencies, however the order in my `:applications` list doesn't seem to have any effect, i.e. it still occurs even with `[:logger, :rollbax, :x]`.

The error being thrown before :rollbax is ready was `18:09:02.570 [error] backend port not found: :inotifywait` which was being thrown by phoenix_live_reload. So I think you'd probably be able to reproduce by generating an exrm release with that in the `:applications` list. Granted, that's a development dependency that shouldn't be included in my release in the first place so I've removed it from my `:applications` which also solves my issue, but I imagine if phoenix_live_reload can sneak in an error message before rollbax is ready then it'd be possible for another dependency to do so.

Thanks for looking into this and thanks again for your work on this library!
Adam

**Comment by whatyouhide** [comment] 2016-06-12 09:44
@adamkittelson the reason we went with checking if `Rollbax.Client` is alive (instead of doing the "registering the backend" dance) is that it also serves the purpose of warning users if they're using Rollbax without having started the `:rollbax` application. If this fixed your error, I would be inclined to close this issue :), wdyt?

**Comment by adamkittelson** [comment] 2016-06-12 17:47
Works for me, thanks again!

**Closed** 2016-06-12 17:48 UTC
